### PR TITLE
Tickets/sitcom-1242

### PR DESCRIPTION
**Pull request by kfanning**
Many changes to slack guidelines. Generally more supportive of observers using channels however best suits them, tries to enhance separation between "project personnel" and "remote support" to keep clutter out of lower tier channels. Added worklogs to diagram.

### CODE REVIEW

**Review by edennihy — COMMENTED** [review]
The original set of commits to the slack-channel-usage provides a nice clarification, thanks for this. However, there is a second set of commits pushed by @isotuela , where did these come from? I don't think they should be merged with this PR. I will hold off on approving until that is resolved.

**Comment by kfanning** [comment]
> The original set of commits to the slack-channel-usage provides a nice clarification, thanks for this. However, there is a second set of commits pushed by @isotuela , where did these come from? I don't think they should be merged with this PR. I will hold off on approving until that is resolved.



> The original set of commits to the slack-channel-usage provides a nice clarification, thanks for this. However, there is a second set of commits pushed by @isotuela , where did these come from? I don't think they should be merged with this PR. I will hold off on approving until that is resolved.

The second set come from a rebase with tickets/SITCOM-1355 which includes fixes for the links. That is why the earlier build broke, because there are many broken links present in main. Once that is merged, those commits should be in main and then this should smoothly be ready to be merged into main.

**Comment by edennihy** [comment]
Got it, thanks for the clarification. So the plan is to re-based when SITCOM-1355 is merged into main and adding the commits here was just to double-check the build?

**Comment by edennihy** [comment]
Just want to be sure I am reviewing the correct parts.

**Comment by kfanning** [comment]
Exactly. I can't speak for how it will look when it SITCOM-1355 is merged and this is based on main again though. Hopefully it becomes just the original commits.

**Review by edennihy — APPROVED** [review]
Sounds good. In that case, changes approved.

**Pull request merged**
