### PR TITLE
Tickets/sitcom 316

### PR DESCRIPTION
**Pull request by isotuela**
First draft of the trunk of the tree of the main page.

### CODE REVIEW

**Review by Slimleashma — COMMENTED** [review]
Can I see the html mockup?

**Comment by isotuela** [comment]
https://obs-ops.lsst.io/v/SITCOM-316/index.html  should show the mock up html, now working.

**Comment by Slimleashma** [comment]
I think this looks great!

**Review by tribeiro — APPROVED** [review]
Looks good! Thanks for the updates!

**Pull request merged**
